#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

source_file="$1"
server_ip="$2"
username="$3"
private_key_arg="$4"
scp_args="-o StrictHostKeyChecking=no"

if [$# -lt 3]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	else
		scp $scp_args $private_key_arg "$source_file" "$username@$server_ip:~/"
fi
