#!/usr/bin/env bash
#write a Bash script that configures a new Ubuntu machine to
#Nginx should be listening on port 80,
#querying Nginx at its root / with a GET request (requesting a page),
#using curl, it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
