#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”


sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
REDIRECT_301="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/server_name _;/REDIRECT_301/" /etc/nginx/sites-enabled/default
sudo service nginx restart
